### ISSUE TITLE
Skia issue causes crash on ios

### ISSUE THREAD

**Issue by kairon007** [MultiplatformKickstarter/Adoptme#12]
`Uncaught Kotlin exception: kotlin.native.internal.IrLinkageError: Function 'beginRecording' can not be called: No function found for symbol 'org.jetbrains.skia/PictureRecorder.beginRecording|beginRecording(org.jetbrains.skia.Rect){}[0]'

    at 0   iosApp                              0x104ce5f9b        kfun:kotlin.Throwable#<init>(kotlin.String?){} + 119 

    at 1   iosApp                              0x104cdf2e3        kfun:kotlin.Error#<init>(kotlin.String?){} + 115 

    at 2   iosApp                              0x104d1c06f        kfun:kotlin.native.internal.IrLinkageError#<init>(kotlin.String?){} + 115 

    at 3   iosApp                              0x104d1c127        kfun:kotlin.native.internal#ThrowIrLinkageError(kotlin.String?){}kotlin.Nothing + 163 

    at 4   iosApp                              0x105aacc07        kfun:androidx.compose.ui.window.MetalRedrawer.draw#internal + 2059 

    at 5   iosApp                              0x105aac373        kfun:androidx.compose.ui.window.MetalRedrawer#drawSynchronously(){} + 203 

    at 6   iosApp                              0x105ab1c63        kfun:androidx.compose.ui.window.RenderingUIView.updateMetalLayerSize#internal + 4183 

    at 7   iosApp                              0x105ab0b83        kfun:androidx.compose.ui.window.RenderingUIView#objc:layoutSubviews + 215 

    at 8   iosApp                              0x105ab2d73        _6f72672e6a6574627261696e732e636f6d706f73652e75693a75692f6f70742f6275696c644167656e742f776f726b2f386132303736303934356430616562612f636f6d706f73652f75692f75692f7372632f75696b69744d61696e2f6b6f746c696e2f616e64726f6964782f636f6d706f73652f75692f77696e646f772f52656e646572696e675549566965772e75696b69742e6b74_knbridge70 + 143 

    at 9   UIKitCore                           0x1a5e810f7        <redacted> + 1527 

    at 10  QuartzCore                          0x1a52abe2f        <redacted> + 503 

    at 11  QuartzCore                          0x1a52ab9b3        <redacted> + 147 

    at 12  QuartzCore                          0x1a52b1bb3        <redacted> + 463 

    at 13  QuartzCore                          0x1a52ab1bb        <redacted> + 647 

    at 14  UIKitCore                           0x1a6167d3f        <redacted> + 35 

    at 15  CoreFoundation                      0x1a3c096b7        <redacted> + 27 

    at 16  CoreFoundation                      0x1a3c07eab        <redacted> + 355 

    at 17  CoreFoundation                      0x1a3c05d9b        <redacted> + 847 

    at 18  CoreFoundation                      0x1a3c05967        CFRunLoopRunSpecific + 607 

    at 19  GraphicsServices                    0x1e7efb4df        GSEventRunModal + 163 

    at 20  UIKitCore                           0x1a6078edb        <redacted> + 887 

    at 21  UIKitCore                           0x1a6078517        UIApplicationMain + 339 

    at 22  SwiftUI                             0x1a8a3f85f        <redacted> + 599 

    at 23  SwiftUI                             0x1a8a3f6a7        <redacted> + 159 

    at 24  SwiftUI                             0x1a865b9fb        <redacted> + 363 

    at 25  iosApp                              0x10465c46f        $s6iosApp6iOSAppV5$mainyyFZ + 39 

    at 26  iosApp                              0x10465c51b        main + 11 

    at 27  dyld                                0x1c7126d83        <redacted> + 2239 

Process finished with exit code 134 (interrupted by signal 6:SIGABRT)
`

**Comment by ferranpons** [comment]
@kairon007 please could you tell me how to reproduce the error? Did you use the emulator or a device?

**Comment by kairon007** [comment]
@ferranpons I use a real device and the app launches but crashes at the very start. Please let me know if you need any other info

**Comment by ferranpons** [comment]
@kairon007 ok, I'll check it on a device. Thanks.

**Comment by ferranpons** [comment]
@kairon007 I have upgraded the project to Kotlin 2.0.0. Please try to check if it's still crashing on start. Thanks!

**Comment by kairon007** [comment]
@ferranpons  Works like a charm. Thank you. Eagerly waiting for the pro version when you release it
